config/routes.rb
Crappr::Application.routes.draw do
  resources :suburbs, :only => [:show, :index] do
    resources :toilets, :only => [:index]
  end

  resources :reviews, :only => [:index]
  resources :toilets, :only => [:show, :index] do
    resources :reviews, :only => [:index, :create]
  end
  
  match "about" => "pages#about"
  root :to => "pages#home"
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :name, :value, :text

  # Associations
  belongs_to :toilet
  
  default_scope order('created_at desc')
  
  # Validations
  validates_presence_of :value, :name
  
  # Value needs to be a number
  validates_numericality_of :value, :greater_than => 0, :less_than_or_equal_to => 5
  
end

app/models/suburb.rb
class Suburb < ActiveRecord::Base

  attr_accessible :name
  
  # Associations
  has_many :toilets
  validates_presence_of :name
  
  default_scope order('name asc')
  
  def to_param
    "#{self.id}-#{ActiveSupport::Inflector.transliterate(self.name).parameterize}"
  end
  
end

app/models/toilet.rb
class Toilet < ActiveRecord::Base
  include HasLocation
  include ToiletsHelper
  
  # Associations
  has_many :reviews
  belongs_to :suburb
  
  # Validations
  validates_presence_of :location
  validates_numericality_of :lat, :greater_than_or_equal_to => -90.0, :less_than_or_equal_to => 90.0
  validates_numericality_of :lng, :greater_than_or_equal_to => -180.0, :less_than_or_equal_to => 180.0
  
  # Scopes
  scope :top_ids, lambda { |limit|
        joins(:reviews).
        select('toilets.id').
        group('toilets.id').
        order('AVG(reviews.value) desc').
        limit(limit)
    }

  scope :in_suburb, lambda { |suburb_id| 
    suburb_id ? where(:suburb_id => suburb_id) : where('1=1')
  }

  scope :nearby, lambda { |lat, lng|
    return scoped unless lat && lng
    default_range = 500
    near(:origin => [lat.to_f, lng.to_f], :within => default_range)
  }  

  # Class Methods
  def self.top(num)
    return scoped if num.nil?
    self.where(:id => top_ids(num))
  end
  
  # Instance Methods   
  def rating
    reviews.average(:value).try(:round) 
  end
  
  def rating_count
    reviews.count
  end
  
  # Dirty hack!! 
  # Found issue here: https://rails.lighthouseapp.com/projects/8994/tickets/4840-to_xml-doesnt-work-in-such-case-eventselecttitle-as-tto_xml
  # TODO: fix later
  def dist
    if respond_to?(:distance)
      distanceize(distance, "m", false)
    end
  end
                    
  def to_param
    "#{self.id}-#{ActiveSupport::Inflector.transliterate(self.location).parameterize}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :prepare_for_mobile
  helper_method :mobile_device?
  
  private

  def mobile_device?
    return false if request.format == "json"
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/ && !(request.user_agent =~ /iPad/)
    end
  end

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end
  
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  respond_to :html, :mobile
  
  def index
    respond_with @toilets = Toilet.top(10)
  end
  
  def about
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html, :mobile
  
  def home
    respond_with @toilets = Toilet.top(10)
  end
  
  def about
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  respond_to :js

  def index
    @reviews = toilet.reviews
    render :json => @reviews 
  end

  def create
    @review = toilet.reviews.create(params[:review])
    if @review.valid?
      flash[:notice] = "Thank you for reviewing this toilet"
    else
      flash[:error] = "Unable to add review. Please ensure you have selected a rating and name."
    end

    respond_to do |format|
      format.js { render }
      format.json { render :json => @review }
    end
  end

  def toilet
    @toilet ||= Toilet.find(params[:toilet_id])
  end
end

app/controllers/suburbs_controller.rb
class SuburbsController < ApplicationController
  respond_to :html, :mobile, :json
  before_filter :load_suburb, :except => [:index]
  
  def index
    respond_with @suburbs = Suburb.all
  end

  def show
    respond_to do |format|
      format.mobile { render :template => 'suburbs/mobile/show' }
      format.json   { rener  :json => @suburb }
      format.all
    end
  end
  
  private
  
  def load_suburb
    @suburb = Suburb.find(params[:id])
  end
  
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  respond_to :html, :js, :mobile
  before_filter :load_toilet, :except => [:index]

  def index
    @toilets = Toilet.scoped
      .in_suburb(params[:suburb_id])
      .nearby(params[:lat], params[:lng])
      .top(params[:top])
      .limit(params.fetch(:limit, nil))
    @toilets = @toilets.paginate(:page => params[:page]) if params[:page]
    respond_to do |format|
      format.mobile { render :template => 'toilets/mobile/index' }
      format.json   { render :json => @toilets, :methods => [:dist, :rating, :rating_count] }
      format.all
    end
  end

  def show
    @near_toilets = Toilet.near(:origin => @toilet, :within => 0.5).order("distance asc")
    @reviews = @toilet.reviews.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.mobile { render :template => 'toilets/mobile/show' }
      format.json { render :json => @toilet, :methods => [:dist, :rating]}
      format.all
    end
  end

  private

  def load_toilet
    @toilet = Toilet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_mobile?
    request.user_agent =~ /Mobile|webOS|Android|iPhone/i && !(request.user_agent =~ /iPad/)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/toilets_helper.rb
module ToiletsHelper
  def distanceize(km, to="m", display_type=true)
    case to
    when "m"
      new_distance = km.to_f * 1000
    when "km"
      new_distance = km.to_f
    else # m
      new_distance = km.to_f * 1000
    end
    to = "" unless display_type
    sprintf("%20.4g#{to}", new_distance)
  end
end

app/views/headers/_main.html.erb
<div id="masthead">
  <div class="inner">
	<div class="container">
		<h1>Crappr</h1>
		<p class="lead">
		  ... Well, The public ones at least.<br>
		</p>
		<p>
			An index of the public toilets of Wellington.
		</p>
  </div>
</div>
</div>

app/views/index/index.html.erb
<% content_for :header do %>
	<%= render(:partial => 'headers/main') %>
<% end %>

<section id="top-10">
  <div class="page-header">
    <h1>Top 10 Crapprs <small>As voted by you!</small></h1>
  </div>
  
  <div id="information">
	<h2></h2>
	<ol>
		<%= render(:partial => 'toilet_li', :collection => @toilets) %>
	</ol>
  </div>
  <div id="map_div" class="top-10"></div>
</section>

<script type='text/javascript'>
	
    $(function()
    {
		set_map_height_to(500);
		drawMap(174.613088, -41.613483, 175.00124, -40.873161, google.maps.MapTypeId.TERRAIN, 11);
		getMarkersFor('/api/toilets/top_10.json', false);
    });

</script>

<% content_for :footer do %>

  <div class="inner">
	<div class="container">
		<p>
        	Designed and built with all the love in the world by me :)
		</p>
  </div>
</div>
<% end %>

app/views/index/index.mobile.erb
<% content_for :header do %>
	<div  class="homepage">
		<h1><a href="/">Crappr</a></h1> 
		<h2>Find a Crapper Near You</h2>
	</div>
<% end %>

<div class="home">

	<button id='gps-btn' class="button home-btn">USE GPS</button>
	<h3>- OR -</h3>

	<%= link_to "BROWSE", toilets_url, :class => "button home-btn" %>
	<div id="toilets-homepage-container" style="display:none;">
		<div id='toilets'>
		</div>
	</div>
	
</div>

<% content_for :footer do %>
	<div  class="homepage-footer">
		<%= link_to "Full Site", root_url(:mobile => 0), :rel => "external" %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crappr</title>
  <%= stylesheet_link_tag 'application' %>
  <link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= javascript_include_tag 'application'  %>

  <%= csrf_meta_tag %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25877318-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<div id="container">
	<div class="navbar navbar-fixed-top navbar-inverse">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="brand" href="/">Crappr</a>
	      <ul class="nav">
	        <li class=""><%= link_to "About", about_path %></li>
			<li class=""><%= link_to "Suburbs", suburbs_path %></li>
	        <li class=""><%= link_to "Toilets", toilets_path %></li>
			<% if is_mobile?%>
				<li class=""><%= link_to "Back to Mobile Site", root_url(:mobile => 1), :rel => "external" %></li>
			<% end %>
	      </ul>
	    </div>
	  </div>
	</div>
	
	<div id="header">
		<%= yield :header %>
	</div>
	
	<div id="content" class="container"> 
		<%= yield %>
	</div>
	<div class="clear"></div>
	<div id="footer">
		<%= yield :footer %>
	</div>
</div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= h(yield(:title) || "Crappr") %></title>
	<%= javascript_include_tag 'mobile' %>
	<%= stylesheet_link_tag 'mobile' %>
	<meta name="viewport" content="width=device-width, user-scalable=no" />
    <%= yield(:head) %>
  </head>
  <body>
	<script>

		$(function() {
			<%= yield(:after_load) %>
		});

	</script>
	
	<div id="header"> 
		<%= yield :header %>
	</div>

	<div id="content">
		<%= yield %>
	</div>
	
	<div id="footer">
		<%= yield :footer %>
	</div>
  </body>
</html>

app/views/pages/_toilet_li.html.erb
<li><%= link_to toilet_li.location.html_safe, toilet_li %></li>

app/views/pages/about.html.erb
<% content_for :header do %>
	<%= render(:partial => 'headers/main') %>
<% end %>

<section id="about">
  <div class="page-header">
    <h1>About Crappr <small>Brief history and more!!</small></h1>
  </div>
  <div class="row">
    <div class="span6 columns">
      <h3>History</h3>
      <p>The Crappr website was created by Michael Parreno-Villa during the <a href="http://www.mixandmash.org.nz/" title="mix &amp; mash - the great NZ remix &amp; mashup competition">Mix and Mash competition 2011</a>.</p> 
    </div>
    <div class="span6 columns">
      <h3>Credits</h3>
 		<ul>
			<li><a href="http://data.govt.nz/dataset/show/1137">Wellington City Public Conveniences</a> data used under the Creative Commons Attribution 3.0 New Zealand licence</li>
			<li><a href="http://code.google.com/apis/maps/documentation/javascript/" title="The Google Maps Javascript API V3 - Google Maps JavaScript API V3 - Google Code">Google Maps API V3</a>.</li> 
			<li>All icons of this site were created by Nico Mollet or James Briano and are part of the <a href="http://code.google.com/p/google-maps-icons/" title="google-maps-icons - Project Hosting on Google Code">Google Maps Icons project</a>. Used under the <a href="http://creativecommons.org/licenses/by-sa/3.0/" title="Creative Commons - Attribution-ShareAlike 3.0 Unported">Creative Commons 3.0 BY-SA unported license</a>.</li>
			<li>MarkerClusterer is part of the <a href="http://code.google.com/p/google-maps-utility-library-v3/" title="google-maps-utility-library-v3 - Project Hosting on Google Code">Google Maps Utility Library V3</a> and used under the <a href="http://www.apache.org/licenses/LICENSE-2.0" title="">Apache License 2.0</a>.</li>
		</ul>
    </div>
  </div><!-- /row -->
</section>


<% content_for :footer do %>
  <%= render(:partial => 'shared/footer') %>
<% end %>

app/views/pages/home.html.erb
<% content_for :header do %>
	<%= render(:partial => 'headers/main') %>
<% end %>

<section id="top-10">
  <div class="page-header">
    <h1>Top 10 Crapprs <small>As voted by you!</small></h1>
  </div>
  
  <div id="information">
	<h2></h2>
	<ol>
		<%= render(:partial => 'toilet_li', :collection => @toilets) %>
	</ol>
  </div>
  <div id="map_div" class="top-10"></div>
</section>

<script type='text/javascript'>
	
    $(function()
    {
		set_map_height_to(500);
		drawMap(174.613088, -41.613483, 175.00124, -40.873161, google.maps.MapTypeId.TERRAIN, 11);
		getMarkersFor('/toilets.json?top=10', false);
    });

</script>

<% content_for :footer do %>
  <%= render(:partial => 'shared/footer') %>
<% end %>

app/views/pages/home.mobile.erb
<% content_for :header do %>
	<div  class="homepage">
		<h1><a href="/">Crappr</a></h1> 
		<h2>Find a Crapper Near You</h2>
	</div>
<% end %>

<div class="home">

	<button id='gps-btn' class="button home-btn">USE GPS</button>
	<h3>- OR -</h3>

	<%= link_to "BROWSE", toilets_url, :class => "button home-btn" %>
	<div id="toilets-homepage-container" style="display:none;">
		<div id='toilets'>
		</div>
	</div>
	
</div>

<% content_for :footer do %>
	<div  class="homepage-footer">
		<%= link_to "Full Site", root_url(:mobile => 0), :rel => "external" %>
	</div>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for [@toilet, @review ||= Review.new], :remote => true do |f| %>
  <fieldset>
  <legend>Write a Review:</legend>
  <div class="clearfix">
    <%= f.label :name %>
    <div class="input"><%= f.text_field :name %></div>
  </div>
  <div class="clearfix">
    <%= f.label :text, "Review" %>
    <div class="input"><%= f.text_area :text, :rows => 8 %></div>
  </div>
  <div class="clearfix">
    <%= f.label :value, "Rating" %>
    <div class="input">
		<ul class="radio-rating">
			<% (1..5).each do |i| %>
				<li>
					 <%= "#{i}" %> <%= f.radio_button :value, i %> |
				</li>
			<% end %>
		</ul>
	</div>
  </div>
	
  <div class="actions">
    <button type="submit" class="btn primary">Add Review</button>
   </div>
</fieldset>
<% end %>

app/views/suburbs/index.html.erb
<section id="toilet">
  <div class="page-header">
    <h1>Browse by Suburb:</h1>
  </div>
  <ul>
	<% @suburbs.each do |suburb| %>
		<li><%= link_to suburb.name, suburb_path(suburb) %></li>
		<% end %>
  </ul>
</section>

app/views/toilets/mobile/show.mobile.erb
<% content_for :header do %>
	<h1><a href="/">Crappr</a></h1>
<% end %>

<% content_for :after_load do %>
$(".nav-tabs li").click(function() { 
	$(".nav-tabs li").removeClass('active');
	$(this).addClass('active');
	
	$("section#toilet div").not('.page-header').hide();
	
	var funct = $(this).children('a').attr('data-function');
	window[funct]();
	return false;
});

$('#show-form, #cancel').click(function(){
	$('#reviews_add_form').toggle();
	$('#reviews_add').toggle();
	return false;
});

jQuery.fn.submitWithAjax = function() {
  this.submit(function() {
    $.post(this.action, $(this).serialize(), function(data){
		$('#reviews_add_form').hide();
		if( $('#reviews_list ul.listview').length ){
			$("#reviews_list ul.listview").prepend(reviewListItem(data.name, data.created_at, data.text, data.value));
			$('#reviews_list ul li').removeClass('top bottom');
			$('#reviews_list ul li:first').addClass('top');
			$('#reviews_list ul li:last-child').addClass('bottom');
		}
		document.reviews_add_form.reset();
	}, "json");
    return false;
  })
  return this;
};

$(document).ready(function() {
  $("form.reviews_add_form").submitWithAjax();
})

<% end %>

<ul class="nav nav-tabs">
  <li class="active"><a href="" data-function='loadDetails'>Info</a></li>
  <li><a href="" data-function='loadMap'>Map</a></li>
  <li><a href="" data-function='loadStreet'>StreetView</a></li>
  <li><a href="" data-function='loadReviews'>Review</a></li>
</ul>

<section id="toilet">
  <div class="page-header">
    <h2><%= @toilet.location.html_safe %></h2>
  </div>
  <div id="info">
  	<p><strong>Opening Hours:</strong> <%= @toilet.open_hours.html_safe %></p>
  	<p><strong>Gender:</strong> <%= @toilet.gender.html_safe %></p>
  	<p><strong>Changing Room?:</strong> <%= (@toilet.change_rm) ? "Yes" : "No" %></p>
  	<p><strong>Disabled?:</strong> <%= (@toilet.disabled) ? "Yes" : "No" %></p>
	<p class="left"><strong>Rating:</strong></p>
		<ul class="star-rating left">
		<% (1..5).each do |i| %>
			<li>
				<span class="<%="stars-#{i} #{ "current-rating" if i == @toilet.rating }" %>"></span>
			</li>
		<% end %>
	</ul>

	<p class="small rating-count">(<%= @toilet.reviews.count %> ratings)</p>
    <div class="clear"></div>
	<hr class='divider'/>
  	<p><%= link_to 'Open Map', "http://maps.google.com/maps?q=#{@toilet.lat},#{@toilet.lng}"  %></p>
	<hr class='divider'/>
  	<p><%= link_to 'Back to all', toilets_path %></p>
  </div>
  <div id="map_div" class="" style='display:none;'>Google Maps</div>
  <div id="pana" class="" style='display:none;'>Google StreetView</div>
  <div id="reviews" class="" style='display:none;'>
	<div id="reviews_add" class="" style='display:block;'>
		<%= link_to "ADD A REVIEW", toilets_url, :class => "button home-btn", :id => "show-form"%>
	</div>
	<div id="reviews_add_form" class="" style='display:none;'>

		<%= form_tag toilet_reviews_path(@toilet, :format => 'json'), :class => 'reviews_add_form', :name => 'reviews_add_form' do %>
		  <fieldset>
		  <legend>Write a Review:</legend>
		  <div class="clearfix">
		    <%= label_tag 'review[name]', 'Name' %>
		    <div class="input"><%= text_field_tag 'review[name]' %></div>
		  </div>
		  <div class="clearfix">
		    <%= label_tag 'review[text]', "Review" %>
		    <div class="input"><%= text_area_tag 'review[text]', '', :rows => 8 %></div>
		  </div>
		  <div class="clearfix">
		    <%= label_tag 'review[value]', "Rating" %>
		    <div class="input">
				<ul class="radio-rating">
					<% (1..5).each do |i| %>
						<li><%= "#{i}" %> <%= radio_button_tag 'review[value]', i %> |</li>
					<% end %>
				</ul>
			</div>
		  </div>

		  <div class="actions">
		    <button type="submit" class="btn primary" id='submit'>Add Review</button>
			<button type="submit" class="btn secondary" id='cancel'>Cancel</button>
		   </div>
		</fieldset>
		<% end %>
	</div>	
	<div id="reviews_list" class="">
	</div>
  </div>
</section>


<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>


function loadDetails(){
  $("#info").show();
  //Update the toilet stars rating :)
  $.getJSON('/toilets/<%= @toilet.id %>.json', function(data) {
	$('#toilet .star-rating').html(drawStars(data.toilet.rating));
	$('#toilet .rating-count').html("("+data.toilet.rating_count+" ratings)");
  });
}

function loadReviews(){
  $("#reviews").show();
  $("#reviews div").not('#reviews_add_form').show();
	
  $.getJSON('/toilets/<%= @toilet.id %>/reviews.json', function(data) {
  	items = [];

  	$.each(data, function(key, val) {
      items.push(reviewListItem(val.name, val.created_at, val.text, val.value));
  });
	$('#reviews_list').html(  
		$('<ul/>', {
	    	'class': 'listview',
	    	html: items.join('')
	  	})
	);

	$('#reviews_list ul li:first').addClass('top');
	$('#reviews_list ul li:last-child').addClass('bottom');

 });
}
function loadMap(){
  $("#map_div").show();
  set_map_height_to(250);
  var Latlng = new google.maps.LatLng(<%= @toilet.lat %>,<%= @toilet.lng %>);
  drawMap(Latlng, google.maps.MapTypeId.ROADMAP, 1);
  var marker = new google.maps.Marker({ position: Latlng, map: map, title: name,icon: '/assets/toilet.png' });
  markers.push(marker);
  map.setCenter(Latlng);
  map.setZoom(18);
}

function loadStreet(){
  $("#pana").show();
  set_map_height_to(250);
  var webService = new google.maps.StreetViewService();  
  var Latlng = new google.maps.LatLng(<%= @toilet.lat %>,<%= @toilet.lng %>);
  var checkaround = 50;
  webService.getPanoramaByLocation(Latlng,checkaround,checkNearestStreetView);
}

function checkNearestStreetView(panoData){ 
  var Latlng = new google.maps.LatLng(<%= @toilet.lat %>,<%= @toilet.lng %>);
  if(panoData){
       if(panoData.location){
          if(panoData.location.latLng){
             	var panoramaOptions = {
  			  position: panoData.location.latLng, 
  			  pov: {
  			    heading: bearing_from(panoData.location.latLng, Latlng),
  			    pitch: -2,
  			    zoom: 1
  			  }
  			};
  			
  			var panorama = new  google.maps.StreetViewPanorama(document.getElementById("pana"), panoramaOptions);
  			drawMap(Latlng, google.maps.MapTypeId.SATELLITE, 11);
  			map.setStreetView(panorama);
  			map.setCenter(Latlng);
  			map.setZoom(12);
          }
      }
  }
  else 
  {
	alert("Sorry, Google StreetView is unavailable for this Crappr.")
	drawMap(Latlng, google.maps.MapTypeId.SATELLITE, 1, "pana");
	var marker = new google.maps.Marker({ position: Latlng, map: map, title: name,icon: '/assets/toilet.png' });
	markers.push(marker);
	map.setCenter(Latlng);
	map.setZoom(18);
  }
}

</script>

app/views/toilets/show.html.erb
<section id="toilet">
  <div class="page-header">
    <h1><%= @toilet.location.html_safe %></h1>
  </div>
  <div id="information">
	<p><strong>Opening Hours:</strong> <%= @toilet.open_hours.html_safe %></p>
	<p><strong>Gender:</strong> <%= @toilet.gender.html_safe %></p>
	<p><strong>Changing Room?:</strong> <%= (@toilet.change_rm) ? "Yes" : "No" %></p>
	<p><strong>Disabled?:</strong> <%= (@toilet.disabled) ? "Yes" : "No" %></p>
	<p class="left"><strong>Rating:</strong></p>
	<div id="info-rating">
		<%= render :partial => 'rating', :locals => {:toilet =>@toilet } %>
	</div>
	<p><%= link_to 'View all Crapprs', toilets_path %></p>
  </div>
  <div id="map_div" class="show"></div>
  <div id="pana" class="show"></div>
</section>

<div class="clear"></div>

<section id="near">
  <div class="page-header">
    <h1>Crapprs near here:</h1>
  </div>
  	<ul>
		<%= render(:partial => 'near_toilet', :collection => @near_toilets) || 
			"<li>Sorry, there are no toilets near here. This Crappr might just have to do!</li>".html_safe %>
	</ul>	
</section>

<section id="reviews">
  <div class="page-header">
    <h1>Reviews:</h1>
  </div>
  <div id="reviews-list">
  	<%= render(:partial => 'reviews/review', :collection => @reviews.compact)%>
  </div>

  <%= will_paginate @reviews %>
	
  <div id="reviews-alerts"></div>
  <%= render :partial => 'reviews/form' %>
</section>


<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type='text/javascript'>
	
    $(function()
    {
		set_map_height_to(500);
		
		// Close alerts
		$('a.close').live('click', function() {
		  $(this).parent().slideUp('fast');
		  return false;
		});
		// Set up Var	
		var Latlng = new google.maps.LatLng(<%= @toilet.lat %>,<%= @toilet.lng %>);
		var webService = new google.maps.StreetViewService();  
		var checkaround = 50;

		webService.getPanoramaByLocation(Latlng,checkaround,checkNearestStreetView);

		function checkNearestStreetView(panoData){
			/** YAY! There is street view :) **/
			/*
			YO! Fixme
			toilets/92 => PANO=(-41.319858, 174.775759)-Toilet=(-41.31995, 174.775797)
			*/
		    if(panoData){
		         if(panoData.location){
		            if(panoData.location.latLng){
		               	var panoramaOptions = {
						  position: panoData.location.latLng, 
						  pov: {
						    heading: bearing_from(panoData.location.latLng, Latlng),
						    pitch: 10,
						    zoom: 1
						  }
						};
						
						var panorama = new  google.maps.StreetViewPanorama(document.getElementById("pana"), panoramaOptions);
						
						drawMap(174.613088, -41.613483, 175.00124, -40.873161, google.maps.MapTypeId.SATELLITE, 11);

						var text = '<div class="toilet_info">' + 
					             '<h4>' + '<%= @toilet.location.html_safe %>'  + '</h4>' +
					             '</div>';

						var infowindow = new google.maps.InfoWindow({ content: text });
					  	var marker = new google.maps.Marker({ position: Latlng, map: map, title: name });
					  	markers.push(marker);
					  	infowindow.open(map, marker);
					  	google.maps.event.addListener(marker, 'click', function() { infowindow.open(map, marker); });
						
						map.setStreetView(panorama);
						map.setCenter(Latlng);
						map.setZoom(19);

		            }
		        }
		    }
		 	else 
			{
		    	/** Else draaaw map because there is NO STREET VIEW AVALIABLE **/
				$('#map_div').removeClass('show');
				$('#pana').remove();
				drawMap(174.613088, -41.613483, 175.00124, -40.873161, google.maps.MapTypeId.SATELLITE, 11);
				
				var text = '<div class="toilet_info">' + 
		    	         '<h4>' + '<%= @toilet.location %>'  + '</h4>' +
						 '<p>' + 'Sorry bro! <br /> Can\'t StreetView this :('  + '</p>' +
		    	         '</div>';
            	
				var infowindow = new google.maps.InfoWindow({ content: text });
		  		var marker = new google.maps.Marker({ position: Latlng, map: map, title: name });
		  		markers.push(marker);
		  		infowindow.open(map, marker);
		  		google.maps.event.addListener(marker, 'click', function() { infowindow.open(map, marker); });
            	
				map.setCenter(Latlng);
				map.setZoom(19);
			}
		}
		
    }); 
</script>
	